// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZEstate.Infrastructure;

#nullable disable

namespace ZEstate.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827141203_AddChatMessages")]
    partial class AddChatMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.IdentityModels.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Apartment identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric")
                        .HasComment("Apartment budget balance");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasComment("Building identifier");

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasComment("Floor number");

                    b.Property<decimal>("IdealParts")
                        .HasColumnType("numeric")
                        .HasComment("Ideal parts percentage of the building");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("Apartment number");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.ApartmentUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasComment("User identifier");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer")
                        .HasComment("Apartment identifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("Whether the user is currently active in this apartment");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the user joined the apartment");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasComment("Role of the user in this apartment");

                    b.HasKey("UserId", "ApartmentId");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ApartmentUsers");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Building identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Building address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the building was added to the system");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("Unique invite code for residents to join");

                    b.Property<bool>("InviteCodeActive")
                        .HasColumnType("boolean")
                        .HasComment("Whether the invite code currently accepts new registrations");

                    b.Property<DateTime?>("InviteCodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Optional expiration date/time for the invite code");

                    b.Property<int?>("InviteCodeMaxUses")
                        .HasColumnType("integer")
                        .HasComment("Optional maximum number of times the invite code can be used");

                    b.Property<int>("InviteCodeUseCount")
                        .HasColumnType("integer")
                        .HasComment("Number of times the current invite code has been used");

                    b.Property<string>("ManagerId")
                        .HasColumnType("text")
                        .HasComment("The house manager responsible for this building");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Building name");

                    b.Property<DateTime?>("PendingManagerTransferEffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When the pending manager transfer takes effect, unless cancelled first");

                    b.Property<DateTime?>("PendingManagerTransferInitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When the pending manager transfer was initiated");

                    b.Property<string>("PendingManagerTransferToUserId")
                        .HasColumnType("text")
                        .HasComment("User identifier of the pending HouseManager successor, if a transfer is in progress");

                    b.Property<decimal>("QuorumThresholdPercent")
                        .HasColumnType("numeric")
                        .HasComment("Minimum percentage of ideal parts that must vote for a decision to have quorum (ЗУЕС default: 50)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Chat message identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasComment("Building identifier - the chat is one shared channel per building");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Message text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date/time the message was sent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Sender user identifier");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Document identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Access")
                        .HasColumnType("integer")
                        .HasComment("Access level: All or ManagerOnly");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasComment("Building identifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Original file name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("File storage path");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("integer")
                        .HasComment("Meeting identifier, if document is minutes/protocol for a meeting");

                    b.Property<int?>("RepairId")
                        .HasColumnType("integer")
                        .HasComment("Repair identifier, if document belongs to a repair");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Document type: Protocol, Contract, Invoice or Other");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the document was uploaded");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("RepairId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Fee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Fee identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasComment("Fee amount");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasComment("Building identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the fee was created");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date from which the fee is active");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date until which the fee is active");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Fee description");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasComment("How often the fee recurs: OneTime or Monthly");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasComment("Fee priority");

                    b.Property<int?>("RepairId")
                        .HasColumnType("integer")
                        .HasComment("Repair identifier, if fee is related to a repair");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Fee title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Fee type: Fixed, PerIdealPart or Repair");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RepairId");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.InviteCodeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Invite code log entry identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasComment("What kind of change was made to the invite code");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasComment("Building identifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date/time the change was made");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("User identifier of the house manager who made the change");

                    b.Property<string>("NewCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("The invite code after the change, if applicable");

                    b.Property<string>("OldCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("The invite code before the change, if applicable");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("InviteCodeLogs");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.JoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Join request identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer")
                        .HasComment("Apartment identifier the user wants to join");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasComment("Building identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the request was submitted");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Optional note from the user");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Optional reason the house manager gave when rejecting the request");

                    b.Property<int>("RequestedRole")
                        .HasColumnType("integer")
                        .HasComment("Role the user requested when joining (owner or resident/tenant)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the request was reviewed");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Current status of the join request");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("User identifier");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("UserId");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Meeting identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agenda")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Agenda items, one per line");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasComment("Building identifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Meeting description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Meeting end date and time");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Physical location, if not (or in addition to) a video link");

                    b.Property<string>("MeetUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Google Meet link for the meeting");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Meeting start date and time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Current meeting status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Meeting title");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Notification identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date/time the notification was created");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasComment("Whether the recipient has read the notification");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Optional in-app deep link related to the notification");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Notification body");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Short notification title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Recipient user identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Obligation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Obligation identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasComment("Amount due");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer")
                        .HasComment("Apartment identifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the obligation was created");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Due date for the obligation");

                    b.Property<int>("FeeId")
                        .HasColumnType("integer")
                        .HasComment("Fee identifier");

                    b.Property<DateTime?>("Period")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("First day of the month this obligation was generated for (Monthly fees only, used to prevent duplicate generation); null for OneTime fees");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Current payment status");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("FeeId");

                    b.ToTable("Obligations");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Payment identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasComment("Amount paid");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasComment("Payment method used");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Optional note entered when recording the payment");

                    b.Property<int>("ObligationId")
                        .HasColumnType("integer")
                        .HasComment("Obligation identifier");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time of payment");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Stripe transaction identifier, null if paid manually");

                    b.HasKey("Id");

                    b.HasIndex("ObligationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Repair identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("numeric")
                        .HasComment("Actual cost once known; falls back to Budget for cost allocation until set");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric")
                        .HasComment("Planned repair budget");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasComment("Building identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the repair was created");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Repair description");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Current repair status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Repair title");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Vote identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer")
                        .HasComment("Apartment identifier this vote is cast on behalf of");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("User identifier of whoever cast the vote");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasComment("Vote value: Yes, No or Abstain");

                    b.Property<int>("VoteQuestionId")
                        .HasColumnType("integer")
                        .HasComment("Vote question identifier");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the vote was cast");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoteQuestionId", "ApartmentId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.VoteQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Vote question identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the question was created");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When voting closes");

                    b.Property<int>("MeetingId")
                        .HasColumnType("integer")
                        .HasComment("Meeting identifier");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("The question being voted on");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When voting opens");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("VoteQuestions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Apartment", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("Apartments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.ApartmentUser", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Apartment", "Apartment")
                        .WithMany("ApartmentUsers")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Building", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Document", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("Documents")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.HasOne("ZEstate.Infrastructure.Data.Models.Repair", "Repair")
                        .WithMany("Documents")
                        .HasForeignKey("RepairId");

                    b.Navigation("Building");

                    b.Navigation("Meeting");

                    b.Navigation("Repair");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Fee", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("Fees")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.Models.Repair", "Repair")
                        .WithMany("Fees")
                        .HasForeignKey("RepairId");

                    b.Navigation("Building");

                    b.Navigation("Repair");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.InviteCodeLog", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("InviteCodeLogs")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.JoinRequest", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Building");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Meeting", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("Meetings")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Notification", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Obligation", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Apartment", "Apartment")
                        .WithMany("Obligations")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.Models.Fee", "Fee")
                        .WithMany("Obligations")
                        .HasForeignKey("FeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Fee");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Payment", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Obligation", "Obligation")
                        .WithMany("Payments")
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obligation");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Repair", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("Repairs")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Vote", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.Models.VoteQuestion", "VoteQuestion")
                        .WithMany("Votes")
                        .HasForeignKey("VoteQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("User");

                    b.Navigation("VoteQuestion");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.VoteQuestion", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Meeting", "Meeting")
                        .WithMany("VoteQuestions")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Apartment", b =>
                {
                    b.Navigation("ApartmentUsers");

                    b.Navigation("Obligations");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Building", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Documents");

                    b.Navigation("Fees");

                    b.Navigation("InviteCodeLogs");

                    b.Navigation("Meetings");

                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Fee", b =>
                {
                    b.Navigation("Obligations");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Meeting", b =>
                {
                    b.Navigation("VoteQuestions");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Obligation", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Repair", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Fees");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.VoteQuestion", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
