// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZEstate.Infrastructure;

#nullable disable

namespace ZEstate.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.IdentityModels.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Apartment identifier");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric")
                        .HasComment("Apartment budget balance");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasComment("Building identifier");

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasComment("Floor number");

                    b.Property<decimal>("IdealParts")
                        .HasColumnType("numeric")
                        .HasComment("Ideal parts percentage of the building");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("Apartment number");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.ApartmentUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("User identifier");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uuid")
                        .HasComment("Apartment identifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("Whether the user is currently active in this apartment");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the user joined the apartment");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasComment("Role of the user in this apartment");

                    b.HasKey("UserId", "ApartmentId");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ApartmentUsers");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Building identifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Building address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the building was added to the system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Building name");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Document identifier");

                    b.Property<int>("Access")
                        .HasColumnType("integer")
                        .HasComment("Access level: All or ManagerOnly");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasComment("Building identifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Original file name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("File storage path");

                    b.Property<Guid?>("RepairId")
                        .HasColumnType("uuid")
                        .HasComment("Repair identifier, if document belongs to a repair");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Document type: Protocol, Contract, Invoice or Other");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the document was uploaded");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RepairId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Fee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Fee identifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasComment("Fee amount");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasComment("Building identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the fee was created");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date from which the fee is active");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date until which the fee is active");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Fee description");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasComment("Fee priority");

                    b.Property<Guid?>("RepairId")
                        .HasColumnType("uuid")
                        .HasComment("Repair identifier, if fee is related to a repair");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Fee title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Fee type: Fixed, PerIdealPart or Repair");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RepairId");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Meeting identifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasComment("Building identifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Meeting description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Meeting end date and time");

                    b.Property<string>("MeetUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Google Meet link for the meeting");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Meeting start date and time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Current meeting status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Meeting title");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Obligation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Obligation identifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasComment("Amount due");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uuid")
                        .HasComment("Apartment identifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the obligation was created");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Due date for the obligation");

                    b.Property<Guid>("FeeId")
                        .HasColumnType("uuid")
                        .HasComment("Fee identifier");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Current payment status");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("FeeId");

                    b.ToTable("Obligations");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Payment identifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasComment("Amount paid");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasComment("Payment method used");

                    b.Property<Guid>("ObligationId")
                        .HasColumnType("uuid")
                        .HasComment("Obligation identifier");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time of payment");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Stripe transaction identifier, null if paid manually");

                    b.HasKey("Id");

                    b.HasIndex("ObligationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Repair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Repair identifier");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric")
                        .HasComment("Repair budget");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasComment("Building identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the repair was created");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Repair description");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Current repair status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Repair title");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when the user registered");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("Whether the user account is active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Full name of the user");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Vote identifier");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasComment("Meeting identifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("User identifier");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasComment("Vote value: Yes, No or Abstain");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the vote was cast");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("UserId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Apartment", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("Apartments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.ApartmentUser", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Apartment", "Apartment")
                        .WithMany("ApartmentUsers")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.Models.User", "User")
                        .WithMany("ApartmentUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Document", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("Documents")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.Models.Repair", "Repair")
                        .WithMany("Documents")
                        .HasForeignKey("RepairId");

                    b.Navigation("Building");

                    b.Navigation("Repair");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Fee", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("Fees")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.Models.Repair", "Repair")
                        .WithMany("Fees")
                        .HasForeignKey("RepairId");

                    b.Navigation("Building");

                    b.Navigation("Repair");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Meeting", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("Meetings")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Obligation", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Apartment", "Apartment")
                        .WithMany("Obligations")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.Models.Fee", "Fee")
                        .WithMany("Obligations")
                        .HasForeignKey("FeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Fee");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Payment", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Obligation", "Obligation")
                        .WithMany("Payments")
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obligation");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Repair", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Building", "Building")
                        .WithMany("Repairs")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Vote", b =>
                {
                    b.HasOne("ZEstate.Infrastructure.Data.Models.Meeting", "Meeting")
                        .WithMany("Votes")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZEstate.Infrastructure.Data.Models.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Apartment", b =>
                {
                    b.Navigation("ApartmentUsers");

                    b.Navigation("Obligations");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Building", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Documents");

                    b.Navigation("Fees");

                    b.Navigation("Meetings");

                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Fee", b =>
                {
                    b.Navigation("Obligations");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Meeting", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Obligation", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.Repair", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Fees");
                });

            modelBuilder.Entity("ZEstate.Infrastructure.Data.Models.User", b =>
                {
                    b.Navigation("ApartmentUsers");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
